# Generated by Django 3.0.6 on 2020-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_fill_with_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
