# Generated by Django 3.0.6 on 2020-05-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(help_text='ФИО абонента', max_length=1000)),
                ('balance', models.IntegerField(help_text='Текущий баланс на счете')),
                ('hold', models.IntegerField(help_text='Холды на счете')),
                ('status', models.BooleanField(help_text='Счет открыт')),
            ],
        ),
    ]
